'use client'
import { useEffect,useState } from 'react'
import { Lake } from '@/lib/types'
import LakeCard from './LakeCard'
import { LocateFixed,Search,SlidersHorizontal,LoaderCircle,RotateCw } from 'lucide-react'
export default function Explorer(){
 const[lakes,setLakes]=useState<Lake[]>([]),[q,setQ]=useState(''),[mode,setMode]=useState(''),[coords,setCoords]=useState<{lat:number,lng:number}|null>(null),[loading,setLoading]=useState(true),[status,setStatus]=useState('Se încarcă locațiile…'),[shown,setShown]=useState(36)
 async function load(c=coords,nextMode=mode){setLoading(true);const p=new URLSearchParams();if(c){p.set('lat',String(c.lat));p.set('lng',String(c.lng))}if(q)p.set('q',q);if(nextMode)p.set('mode',nextMode);try{const r=await fetch('/api/lakes?'+p);const d=await r.json();setLakes(d.lakes||[]);setShown(36);setStatus(c?'Ordonate de la cea mai apropiată':'Permite locația pentru sortare după distanță')}catch{setStatus('Nu am putut încărca locațiile. Încearcă din nou.')}finally{setLoading(false)}}
 useEffect(()=>{load(null)},[])
 function locate(){if(!navigator.geolocation){setStatus('Browserul nu oferă geolocație.');return}setStatus('Solicităm locația…');navigator.geolocation.getCurrentPosition(p=>{const c={lat:p.coords.latitude,lng:p.coords.longitude};setCoords(c);load(c)},()=>setStatus('Locația nu a fost permisă. Poți căuta manual.'),{enableHighAccuracy:true,timeout:12000,maximumAge:300000})}
 return <><section className="search-panel"><div className="search"><Search size={20}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Caută baltă, județ, localitate sau specie…"/><button onClick={()=>load()}>Caută</button></div><div className="filters"><button className="locate" onClick={locate}><LocateFixed size={18}/>În apropiere</button><span className="hint">{status}</span><div className="mode-filter"><SlidersHorizontal size={17}/><select value={mode} onChange={e=>{const value=e.target.value;setMode(value);load(coords,value)}}><option value="">Toate regimurile</option><option value="retention">Cu reținere</option><option value="catch-release">Fără reținere</option></select></div></div></section><div className="section-heading"><div><p className="eyebrow">BAZĂ SINCRONIZATĂ AUTOMAT</p><h2>Bălți și locuri de pescuit</h2></div><strong>{lakes.length} rezultate</strong></div>{loading?<div className="loading"><LoaderCircle className="spin"/>Se încarcă…</div>:lakes.length?<><div className="grid">{lakes.slice(0,shown).map(l=><LakeCard key={l.id} lake={l}/>)}</div>{shown<lakes.length&&<button className="load-more" onClick={()=>setShown(x=>x+36)}><RotateCw size={18}/>Încarcă mai multe ({lakes.length-shown})</button>}</>:<div className="empty"><Search/><h2>Nu am găsit rezultate</h2><p>Încearcă altă localitate sau elimină filtrul de regim.</p></div>}</>
}
