import {Lake} from './types';
export const lakes:Lake[]=[
{id:'tancabesti',name:'Balta Tâncăbești',county:'Ilfov',locality:'Tâncăbești',lat:44.6768,lng:26.0812,rating:4.5,price:'de la 150 lei / 12h',hours:'06:00–18:00',fish:['Crap','Cteno','Somn','Șalău'],facilities:['Parcare','Toaletă','Foișoare','Închiriere barcă'],description:'Complex de lacuri cunoscut pentru pescuitul la crap și competiții. Verifică regulamentul și rezervarea înainte de plecare.',image:'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1600&q=80',waterType:'Lac privat',access:'Drum accesibil auto',phone:'0722 000 001'},
{id:'moara-vlasiei-2',name:'Moara Vlăsiei 2',county:'Ilfov',locality:'Moara Vlăsiei',lat:44.6364,lng:26.2127,rating:4.6,price:'de la 130 lei / 12h',hours:'05:30–19:00',fish:['Crap','Caras','Cteno'],facilities:['Parcare','Căsuțe','Curent','Grătar'],description:'Baltă populară aproape de București, potrivită atât pentru partide scurte, cât și pentru sesiuni de noapte.',image:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1600&q=80',waterType:'Baltă privată',access:'Acces auto până la stand'},
{id:'sarulesti',name:'Lacul Sărulești',county:'Călărași',locality:'Sărulești',lat:44.4218,lng:26.6436,rating:4.7,price:'în funcție de sector',hours:'Conform rezervării',fish:['Crap','Șalău','Somn','Biban'],facilities:['Cazare','Parcare','Ghid','Barcă'],description:'Lac emblematic pentru pescuit sportiv, cu exemplare mari și sectoare diferite. Regulile pot varia în funcție de eveniment.',image:'https://images.unsplash.com/photo-1511884642898-4c92249e20b6?auto=format&fit=crop&w=1600&q=80',waterType:'Lac de acumulare',access:'Acces controlat'},
{id:'bila-2',name:'Balta Bila 2',county:'Giurgiu',locality:'Schitu',lat:43.9977,lng:25.8469,rating:4.3,price:'de la 100 lei / 12h',hours:'06:00–18:00',fish:['Crap','Caras','Somn'],facilities:['Parcare','Foișoare','Magazin momeli'],description:'O opțiune accesibilă pentru partide de o zi, cu standuri spațioase și acces relativ ușor.',image:'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1600&q=80',waterType:'Baltă privată',access:'Ultimii kilometri pe drum secundar'},
{id:'fundulea-6',name:'Fundulea 6',county:'Călărași',locality:'Fundulea',lat:44.4724,lng:26.5038,rating:4.4,price:'de la 120 lei / 12h',hours:'05:00–20:00',fish:['Crap','Cteno','Caras'],facilities:['Parcare','Toaletă','Standuri numerotate'],description:'Baltă orientată spre pescuit la crap, cu perioade bune în special dimineața și spre apus.',image:'https://images.unsplash.com/photo-1497436072909-f5e4be1713c0?auto=format&fit=crop&w=1600&q=80',waterType:'Baltă privată',access:'Acces auto'},
{id:'doripesco',name:'Doripesco',county:'Brașov',locality:'Hălchiu',lat:45.7692,lng:25.5486,rating:4.6,price:'verifică pachetul ales',hours:'Conform sectorului',fish:['Crap','Păstrăv','Somn','Știucă'],facilities:['Restaurant','Cazare','Parcare','Evenimente'],description:'Complex pescăresc cu mai multe amenajări și servicii, potrivit și pentru ieșiri de familie.',image:'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1600&q=80',waterType:'Complex piscicol',access:'Acces facil'}
];
export const getLake=(id:string)=>lakes.find(l=>l.id===id);
export function distanceKm(aLat:number,aLng:number,bLat:number,bLng:number){const R=6371,dLat=(bLat-aLat)*Math.PI/180,dLng=(bLng-aLng)*Math.PI/180;const x=Math.sin(dLat/2)**2+Math.cos(aLat*Math.PI/180)*Math.cos(bLat*Math.PI/180)*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
