import { Lake } from './types'
export const seedLakes: Lake[] = [
  {id:'varlaam',slug:'lacul-varlaam',name:'Lacul Varlaam',county:'Giurgiu',locality:'Adunații-Copăceni',latitude:44.2606,longitude:26.0487,description:'Complex de pescuit sportiv cunoscut pentru exemplarele mari de crap și infrastructura bine întreținută.',species:['Crap','Amur'],fishingModes:['catch-release'],openingHours:'Conform rezervării și regulamentului oficial',priceInfo:'Verifică tarifele actuale pe site-ul oficial',website:'https://laculvarlaam.ro',facilities:['Parcare','Pontoane','Cazare','Dușuri'],verificationStatus:'verified',verifiedAt:'2026-07-01',sourceName:'Site oficial',sourceUrl:'https://laculvarlaam.ro',rating:4.8,ratingCount:186},
  {id:'mv2',slug:'moara-vlasiei-2',name:'Moara Vlăsiei 2',county:'Ilfov',locality:'Moara Vlăsiei',latitude:44.6544,longitude:26.2228,description:'Baltă populară pentru crap, cu partide și regulamente diferențiate.',species:['Crap','Amur','Caras'],fishingModes:['retention','catch-release'],openingHours:'Partide de zi/noapte; verifică programul curent',priceInfo:'Tarife diferite în funcție de partidă',website:'https://www.moaravlasiei2.ro',facilities:['Parcare','Pontoane','Toalete'],verificationStatus:'verified',verifiedAt:'2026-07-01',sourceName:'Site oficial',sourceUrl:'https://www.moaravlasiei2.ro',rating:4.6,ratingCount:241},
  {id:'solacolu',slug:'domeniul-solacolu',name:'Domeniul Solacolu',county:'Călărași',locality:'Sărulești',latitude:44.4319,longitude:26.6504,description:'Domeniu de pescuit cu facilități și opțiuni de pescuit recreativ.',species:['Crap','Somn','Șalău','Caras'],fishingModes:['retention','catch-release'],openingHours:'Program sezonier; confirmă înainte de plecare',priceInfo:'Tarife publicate pe site',website:'https://baltasolacolu.ro',facilities:['Cazare','Restaurant','Parcare','Pontoane'],verificationStatus:'verified',verifiedAt:'2026-07-01',sourceName:'Site oficial',sourceUrl:'https://baltasolacolu.ro',rating:4.5,ratingCount:132},
  {id:'nucetu',slug:'lacul-nucetu',name:'Lacul Nucetu',county:'Dâmbovița',locality:'Nucet',latitude:44.7822,longitude:25.5489,description:'Lac amenajat pentru pescuit sportiv, accesibil din zona București–Târgoviște.',species:['Crap','Caras','Somn'],fishingModes:['retention','catch-release'],openingHours:'Verifică programul înainte de deplasare',priceInfo:'Tarife în funcție de tipul partidei',website:'https://laculnucetu.ro',facilities:['Parcare','Foișoare','Toalete'],verificationStatus:'verified',verifiedAt:'2026-07-01',sourceName:'Site oficial',sourceUrl:'https://laculnucetu.ro',rating:4.4,ratingCount:88},
  {id:'corbu',slug:'amenajarea-piscicola-corbu',name:'Amenajarea Piscicolă Corbu',county:'Constanța',locality:'Corbu',latitude:44.3885,longitude:28.6535,description:'Amenajare piscicolă cunoscută pentru competiții și pescuit la crap.',species:['Crap','Amur','Caras'],fishingModes:['retention','catch-release'],openingHours:'Program și acces pe bază de regulament',priceInfo:'Verifică tarifele și sectoarele disponibile',facilities:['Pontoane','Parcare','Cazare în zonă'],verificationStatus:'community-confirmed',verifiedAt:'2026-06-15',sourceName:'Surse publice și comunitate',rating:4.5,ratingCount:174},
  {id:'peris',slug:'lacul-peris',name:'Lacul Periș',county:'Ilfov',locality:'Periș',latitude:44.685,longitude:26.013,description:'Zonă de pescuit în apropierea Bucureștiului, potrivită pentru partide scurte.',species:['Crap','Caras','Biban'],facilities:['Parcare'],verificationStatus:'community-confirmed',verifiedAt:'2026-05-20',sourceName:'Comunitate',rating:4.1,ratingCount:49}
]
