"use client";
import { useMemo, useState } from "react";
import { LakeCard } from "@/components/lakes/lake-card";
import { LakeMap } from "@/components/map/lake-map";
import { Icon } from "@/components/ui/icon";
import { demoLakes } from "@/data/lakes";
import { distanceKm } from "@/lib/geo";
import type { FishingMode, Lake } from "@/types/lake";
type Position={latitude:number;longitude:number}|null; type ViewMode="map"|"list";
const keyFor=(lake:Lake)=>`${lake.name.toLocaleLowerCase("ro")}|${lake.latitude.toFixed(4)}|${lake.longitude.toFixed(4)}`;
export function LakeExplorer(){
 const[query,setQuery]=useState(""); const[mode,setMode]=useState<FishingMode|"all">("all"); const[view,setView]=useState<ViewMode>("map"); const[position,setPosition]=useState<Position>(null); const[liveLakes,setLiveLakes]=useState<Lake[]>([]); const[locationStatus,setLocationStatus]=useState("Folosește locația pentru sortare și descoperire live"); const[loadingLive,setLoadingLive]=useState(false);
 const allLakes=useMemo(()=>{const m=new Map<string,Lake>(); for(const l of demoLakes)m.set(keyFor(l),l); for(const l of liveLakes)m.set(keyFor(l),l); return Array.from(m.values());},[liveLakes]);
 const results=useMemo(()=>{const n=query.trim().toLocaleLowerCase("ro"); return allLakes.filter(l=>{const s=`${l.name} ${l.locality} ${l.county} ${l.species.join(" ")}`.toLocaleLowerCase("ro"); return(!n||s.includes(n))&&(mode==="all"||l.modes.includes(mode));}).map(l=>({lake:l,distance:position?distanceKm(position,{latitude:l.latitude,longitude:l.longitude}):l.distanceKm})).sort((a,b)=>a.distance-b.distance);},[allLakes,mode,position,query]);
 async function discoverNearby(c:{latitude:number;longitude:number}){setLoadingLive(true);setLocationStatus("Căutăm automat locuri de pescuit și corpuri de apă în apropiere...");try{const r=await fetch(`/api/nearby-lakes?lat=${c.latitude}&lon=${c.longitude}&radius=80`);const d=await r.json() as{lakes?:Lake[];error?:string};if(!r.ok)throw new Error(d.error||"Căutarea live nu a răspuns");setLiveLakes(d.lakes||[]);setLocationStatus(`Am descoperit ${d.lakes?.length||0} locații publice în raza de 80 km`);}catch(e){setLocationStatus(e instanceof Error?e.message:"Căutarea live nu a putut fi efectuată");}finally{setLoadingLive(false);}}
 function locateUser(){if(!navigator.geolocation){setLocationStatus("Geolocația nu este disponibilă în acest browser");return;}setLocationStatus("Căutăm poziția ta...");navigator.geolocation.getCurrentPosition(({coords})=>{const next={latitude:coords.latitude,longitude:coords.longitude};setPosition(next);void discoverNearby(next);},()=>setLocationStatus("Permisiunea pentru locație nu a fost acordată"),{enableHighAccuracy:true,timeout:10000});}
 return <><section className="explorer-toolbar" aria-label="Căutare și filtre"><label className="explorer-search"><Icon name="search" size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Caută baltă, localitate, județ sau specie"/></label><button className="location-button" type="button" onClick={locateUser} disabled={loadingLive}><Icon name="location" size={18}/>{loadingLive?"Descoperim...":"Lângă mine"}</button></section>
 <div className="explorer-options"><div className="filter-row" aria-label="Filtre rapide"><button className={mode==="all"?"filter-chip active":"filter-chip"} onClick={()=>setMode("all")} type="button">Toate</button><button className={mode==="retention"?"filter-chip active":"filter-chip"} onClick={()=>setMode("retention")} type="button">Cu reținere</button><button className={mode==="catch-release"?"filter-chip active":"filter-chip"} onClick={()=>setMode("catch-release")} type="button">Fără reținere</button></div><div className="view-switch" aria-label="Tip afișare"><button className={view==="map"?"active":""} onClick={()=>setView("map")} type="button"><Icon name="map" size={16}/>Hartă</button><button className={view==="list"?"active":""} onClick={()=>setView("list")} type="button"><Icon name="home" size={16}/>Listă</button></div></div>
 <p className="explorer-status" aria-live="polite">{locationStatus} · {results.length} rezultate</p>{view==="map"&&results.length>0&&<LakeMap lakes={results} position={position}/>} {view==="list"&&<div className="lake-grid compact-grid">{results.map(({lake,distance})=><LakeCard key={lake.id} lake={lake} compact distance={distance}/>)}</div>} {results.length===0&&<div className="inline-empty-state"><strong>Nicio locație găsită</strong><span>Încearcă alt termen sau permite locația pentru descoperire live.</span></div>}</>;
}
